#JettyPort
server:
  port: 9000

#时区
spring:
  jackson:
    time-zone: GMT+8
  cloud:
    config:
      server:
        git:
          ##项目的git地址
          uri: ${GIT_CONFIG_URL}
  application:
    name: config
  rabbitmq:
    host: rabbitmq
    port: 5672
    username: user
    password: 123456

#JMX
endpoints:
  jmx:
    unique-names: true

management:
  security:
    enabled: false
  health:
    db:
      enabled: false

security:
  basic:
    enabled: false

#eureka url
eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_SERVER_ADDRES}