server:
  port: 9000

spring:
  jackson:
    #jackson 时区
    time-zone: GMT+8
  cloud:
    config:
      server:
        git:
          ##项目的git地址
          uri: https://git.ylapl.cn/angle/config
          username: angle
          password: yangle123
  application:
    name: config
  #设置config server 用户名、密码
  security:
    user:
      name: admin
      password: 123456

eureka:
  client:
    service-url:
      defaultZone: http://admin:123456@eureka-service:9001/eureka/
  instance:
    prefer-ip-address: true

#admin 允许监控所有接口
management:
  endpoints:
    web:
      exposure:
        include: "*"