server:
  port: 9000

spring:
  jackson:
    #jackson 时区
    time-zone: GMT+8
  cloud:
    config:
      server:
        git:
          ##项目的git地址
          uri: https://git.ylapl.cn/angle/config
          username: angle
          password: yangle123
  application:
    name: config

eureka:
  client:
    service-url:
      defaultZone: http://admin:123456@eureka-service:9001/eureka/
  instance:
    prefer-ip-address: true