version: "3"
services:

  admin:
    image: angley/springboot-admin
    hostname: admin
    environment:
      - spring.cloud.config.profile=prod
      - EUREKA_SERVER_ADDRESS=eureka
    networks:
      - eureka-net

  one:
    image: angley/springboot-one
    hostname: one
    links:
      - admin
    environment:
      - spring.cloud.config.profile=prod
      - EUREKA_SERVER_ADDRESS=eureka
    networks:
      - eureka-net

  two:
    image: angley/springboot-one
    hostname: two
    links:
      - admin
    environment:
      - spring.cloud.config.profile=prod
      - EUREKA_SERVER_ADDRESS=eureka
    networks:
      - eureka-net

  apigetway:
    image: angley/springboot-apigetway
    hostname: apigetway
    ports:
      - "9004:9004"
    links:
      - admin
      - one
      - two
    environment:
      - spring.cloud.config.profile=prod
      - EUREKA_SERVER_ADDRESS=eureka
    networks:
      - eureka-net

networks:
  eureka-net:
    external:
      name: eureka-net
