netflix:
  image: angley/springboot-netflix
  ports:
   - "9003:9003"

config:
  image: angley/springboot-config
  ports:
   - "9002:9002"
  links:
   - netflix

admin:
  image: angley/springboot-admin
  links:
    - netflix
    - config

one:
  image: angley/springboot-one
  links:
    - netflix
    - config
    - admin

two:
  image: angley/springboot-one
  links:
    - netflix
    - config
    - admin

apigetway:
  image: angley/springboot-apigetway
  ports:
    - "9004:9004"
  links:
    - netflix
    - config
    - admin
    - one
    - two


