version: "3"
services:

  eureka1:
    image: registry.cn-hangzhou.aliyuncs.com/angle/netflix
    networks:
      eureka-net:
        aliases:
          - eureka
    ports:
      - "9101:9001"
    hostname: eureka1
    environment:
      - ADDITIONAL_EUREKA_SERVER_LIST=http://eureka2:9001/eureka,http://eureka3:9001/eureka
      - hostName=eureka1
      - IP_ON_OF=true

  eureka2:
    image: registry.cn-hangzhou.aliyuncs.com/angle/netflix
    networks:
      eureka-net:
        aliases:
          - eureka
    ports:
      - "9102:9001"
    hostname: eureka2
    environment:
      - ADDITIONAL_EUREKA_SERVER_LIST=http://eureka1:9001/eureka/,http://eureka3:9001/eureka
      - hostName=eureka2
      - IP_ON_OF=true

  eureka3:
    image: registry.cn-hangzhou.aliyuncs.com/angle/netflix
    networks:
      eureka-net:
        aliases:
          - eureka
    ports:
      - "9103:9001"
    hostname: eureka3
    environment:
      - ADDITIONAL_EUREKA_SERVER_LIST=http://eureka2:9001/eureka/,http://eureka1:9001/eureka
      - hostName=eureka3
      - IP_ON_OF=true

networks:
  eureka-net:
    external:
      name: eureka-net

