version: "3"
services:

  config:
    image: angley/springboot-config
    hostname: config
    ports:
      - "9002:9002"
    environment:
      - spring.cloud.config.profile=prod
      - EUREKA_SERVER_ADDRESS=eureka
    networks:
      - eureka-net

networks:
  eureka-net:
    external:
      name: eureka-net

