version: "3"
services:

  config:
    image: registry.cn-hangzhou.aliyuncs.com/angle/config
#    hostname: config
    ports:
      - "9000:9000"
    environment:
      - EUREKA_SERVER_ADDRES=http://eureka:9001/eureka
      - DGIT_CONFIG_URL=http://git.ylapl.cn/angle/config.git
    networks:
      - eureka-net

networks:
  eureka-net:
    external:
      name: eureka-net

