version: "3"
services:

  config:
    image: registry.cn-hangzhou.aliyuncs.com/angle/config
    hostname: config
    ports:
      - "9002:9002"
    environment:
      - EUREKA_SERVER_ADDRES=http://eureka:9001/eureka
    networks:
      - eureka-net

networks:
  eureka-net:
    external:
      name: eureka-net

