version: "3"
services:

  hongkongConfig1:
    image: angley/springboot-config
    hostname: hongkongConfig1
    ports:
        - 9002:9002
    environment:
      - spring.cloud.config.profile=prod
      - EUREKA_SERVER_ADDRESS=eureka
    networks:
      - dockercoins
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.labels.zone != HongKong

networks:
  dockercoins:
    #external: true
