version: "3"
services:

  hongkongEureka1:
    image: angley/springboot-netflix
    networks:
      dockercoins:
        aliases:
          - eureka
    hostname: hongkongEureka1
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.labels.zone != HongKong
    environment:
      - eureka.client.serviceUrl.defaultZone=http://hongkongEureka2:9003/eureka/

  hongkongEureka2:
    image: angley/springboot-netflix
    ports:
        - 9003:9003
    networks:
      dockercoins:
        aliases:
          - eureka
    hostname: hongkongEureka2
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.labels.zone != HongKong
    environment:
      - eureka.client.serviceUrl.defaultZone=http://hongkongEureka1:9003/eureka/

networks:
  dockercoins:
    #external: true
