version: "3"
services:

  redis:
    image: redis
    ports:
      - "6379:6379"
    networks:
      - eureka-net

  mysql:
    image: mysql
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=123456
    volumes:
      - /Users/Angle/project/dockerData/mysql:/var/lib/mysql
    networks:
      - eureka-net

  rabbitmq:
    image: rabbitmq:management
    hostname: rabbitmq1
    ports:
      - "15672:15672"
      - "5672:5672"
    environment:
      - RABBITMQ_DEFAULT_USER=user
      - RABBITMQ_DEFAULT_PASS=123456
    networks:
      - eureka-net

networks:
  eureka-net:
    external:
      name: eureka-net
