#端口
server:
  port: 9001

eureka:
  client:

    #判断是否注册自身
    registerWithEureka: true
    fetchRegistry: true

    #其它eureka地址
    serviceUrl:
      defaultZone: ${ADDITIONAL_EUREKA_SERVER_LIST}

  server:
    eviction-interval-timer-in-ms: 3000
    #自我保护模式
    enable-self-preservation: true
  instance:
    prefer-ip-address: false

#serviceID
spring:
  application:
      name: eureka
  rabbitmq:
    host: rabbitmq
    port: 5672
    username: user
    password: 123456
