#端口
server:
  port: 9002

#注释此行，自动去检测主机名
#eureka:
#  instance:
#    hostname: one


eureka:
  client:

    #判断是否注册自身
    registerWithEureka: true
    fetchRegistry: true

    #其它eureka地址
    serviceUrl:
      defaultZone: ${ADDITIONAL_EUREKA_SERVER_LIST}

  server:
    eviction-interval-timer-in-ms: 3000
  instance:
    prefer-ip-address: false

#serviceID
spring:
  application:
      name: eureka
#自我保护模式
#eureka:server:enable-self-preservation=false


