#端口
server:
  port: 9001

#注释此行，自动去检测主机名
#eureka:
#  instance:
#    hostname: one


eureka:
  client:

    #判断是否注册自身
    registerWithEureka: false
    fetchRegistry: false

    #其它eureka地址
    serviceUrl:
      defaultZone: ${ADDITIONAL_EUREKA_SERVER_LIST}

  server:
    eviction-interval-timer-in-ms: 3000
    #自我保护模式
    enable-self-preservation: false
  instance:
    prefer-ip-address: false

#serviceID
spring:
  application:
      name: eureka

